In [1]:
import numpy as np


In [2]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


printing array reversely

In [3]:
arr = np.array([[1,2,3],[4,5,6]])
i = len(arr)-1
while i>= 0:
    print(arr[i])
    i -= 1
    


[4 5 6]
[1 2 3]


Reversing an array (out of place): maane copying rki into another new array reversely

In [5]:
def reverse_out_of_place(arr):
    arr2 = np.zeros(len(arr), dtype=int) # creating a new array
    i = 0

    while (i <= len(arr) - 1): # checking if i is less than the last index of array arr
        arr2[i] = arr[len(arr) - 1 - i] # ekhane -i is subtracting the current index from last index. So last theke traverse hocche.
        i += 1

    return arr2

arr= np.array([1, 2, 3, 4])
print(reverse_out_of_place(arr))

arr= np.array([1, 2, 3, 4, 5])
print(reverse_out_of_place(arr))

[4 3 2 1]
[5 4 3 2 1]


Reversing an array(in place): this is basically swapping

In [6]:
def reverse_inPlace(arr):
    x = 0 
    j = len(arr)-1 
    for i in range(len(arr)//2):
        temp = arr[i] # arr er elem aage ekta temp e rekhe nicchi
        arr[i]=arr[j] # last index er elem gula 
        arr[j]=temp
        x += 0
        j -= 1
    return arr

arr = np.array([1, 2, 3, 4])
print(reverse_inPlace(arr))

arr = np.array([1, 2, 3, 4, 5])
print(reverse_inPlace(arr))


[4 3 2 1]
[5 4 3 2 1]


In [7]:
def reverse_inPlace(arr):
    for i in range(len(arr)//2):
        temp = arr[i]
        arr[i] = arr[(len(arr)-1)-i]
        arr[(len(arr)-1)-i] = temp 
        
    return arr 

arr = np.array([1, 2, 3, 4])
print(reverse_inPlace(arr))
        

[4 3 2 1]


Resize Array : 
For fixed memory location, we cant resize array. To resize it, first we need to make a new array with a size that we want to resize. 

In [8]:
#import numpy as np
def resize_arr( given_arr, new_size):
    new_arr = np.array([0]*new_size ) # array dte vule gesi 
    for i in range(len(given_arr)):
        new_arr[i]= given_arr[i]
    return new_arr

given_arr =np.array([1,2,3,4]) 

resize_arr(given_arr, 6)

array([1, 2, 3, 4, 0, 0])

#copy Array:

Initializing new array with same length of the given array. Copying the value one by one as just memory location copy  hoy.

In [9]:
import numpy as np
def copy_array( arr):
    new_arr = np.array([0]* len(arr))
    for i in range(len(arr)):
        new_arr[i]= arr[i]
    return new_arr

arr1 = np.array([1,2,3,4])
copy_array(arr1)

        

array([1, 2, 3, 4])

Array shifting:

right shift: must be start from last block. and right side e shorte thakbe. first box blsnk hote thakbe.

basically, im shifting from left to right and iterating from right to left.

In [14]:
def right_shift(arr):
    for i in range(len(arr)-1, 0, -1): # starting from last element. loop is iterating in reverse order.
        arr[i] = arr[i-1]
    arr [0] = 0
    return arr

arr = np.array([1, 2, 3, 4])
print(right_shift(arr))

[0 1 2 3]


left shift:

In [7]:
def left_shift(arr):
    for i in range(1, len(arr),1): # iterating right to left
        arr [i-1] = arr[i] 
    arr[len(arr)-1] = 0
    return arr

arr = np.array([1, 2, 3, 4])
print(left_shift(arr))

[2 3 4 0]


ROTATING

Left rotate: This is equivalent to shifting circular array left. 1st elem will not be lost as it will move to last slot. mane, elem gula baam dike shorte thakbe.

In [9]:
def rotate_left(arr):
    temp = arr[0]  # eta aage kno liklm??? # 1st elem aagei store kre nicchi
    for i in range(1, len(arr),1): # iterating right to left
       
        arr [i-1] = arr[i] 
    arr[len(arr)-1] = temp
    return arr

arr = np.array([1, 2, 3, 4])
print(rotate_left(arr))

[2 3 4 1]


right rotate:

In [12]:
def right_rotate(arr):
    temp = arr[len(arr)-1]
    for i in range( len(arr)-1,0, -1):
       
        arr [i] = arr[i-1] 
    arr[0] = temp
    return arr

arr = np.array([1, 2, 3, 4])
print(right_rotate(arr))

#bujhinai

[4 1 2 3]


Insertion

In [5]:
def resize_arr( given_arr, new_size):
    new_arr = np.array([0]*new_size ) # array dte vule gesi 
    for i in range(len(given_arr)):
        new_arr[i]= given_arr[i]
    return new_arr

# given_arr =np.array([1,2,3,4]) 

# resize_arr(given_arr, 6)






def insert_element_end(arr, size, elem):
    if size >= len(arr):
        arr = resize_arr(arr, len(arr)+5)
    arr[size]= elem
    return arr

arr= np.zeros(4, dtype=int)
arr[0], arr[1], arr[2] = 4, 6, 5
print(arr)
print(insert_element_end(arr, 3, 15)) #array, size, elem
print(insert_element_end(arr, 4, 25)) #array, size, elem


def insert_anywhere(arr, size, index, elem):
    if index < 0 or index > size:
        return "insertion not possible"
    
    if size >= len(arr):
        arr = resize_arr(arr, len(arr)+ 5)
        
    for i in range( size, index, -1):
        arr[i] = arr[i-1]
        arr = 
    

[4 6 5 0]
[ 4  6  5 15]
[ 4  6  5 15 25  0  0  0  0]


Inserting anywhere

In [9]:
def resize_arr( given_arr, new_size):
    new_arr = np.array([0]*new_size ) # array dte vule gesi 
    for i in range(len(given_arr)):
        new_arr[i]= given_arr[i]
    return new_arr


def insert_anywhere(arr, size, index, elem):
          if index<0 or index>size:
                   return "Insertion Not Possible"

          if size >= len(arr):
                  arr= resize_arr(arr, len(arr)+3)

          for i in range(size, index, -1): #Right Shift
                  arr[i]= arr[i-1]

          arr[index]= elem
          return arr

arr= np.zeros(4, dtype=int)
arr[0], arr[1], arr[2] = 4, 6, 5
print(arr)
print(insert_anywhere(arr, 3, 1, 15)) #array, size, index, elem
print(insert_anywhere(arr, 4, 4, 25)) #array, size, index, elem, the size increased


# If you want to insert at the end with this function too,
# all you have to do is provide the index value equal to the size


[4 6 5 0]
[ 4 15  6  5]
[ 4 15  6  5 25  0  0]


Removing

In [ ]:
def rmv_elem( arr, idx, size):
    if size == 0 or (idx < 0 and idx => size):
        return "deletion not possible"
    
    for i in range (idx+1, size):
        arr[i-1] = arr [i]
    arr[size-1]= None
    return arr

arr = np.zeros(5, dtype=int)
arr[0], arr[1], arr[2], arr[3] = 4,5,6,2
print(arr)
print(rmv_elem(arr, 4, 0)) 